spring.application.name=Terceros
server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,utn.frp.comp.terceros

# Vaadin in production mode (set to false for development)
vaadin.productionMode=false

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/terceros01
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=terceros01
spring.datasource.password=654321

# JPA config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
